version: '3'

services:
  angular: 
    build: frontend
    ports:
      - "4200:4200"

  express:
    build: backend
    ports:
      - "3000:3000"
    networks: 
      - net
    depends_on: 
      - database

  database: 
    image: mongo 
    ports:
      - "27017:27017"
    networks: 
      - net
    restart: always

networks: 
  net:
    